### ISSUE TITLE
how can i get 'swap txns'

### ISSUE THREAD

**Issue by nnnggel** [reach-sh/humble-sdk#43]
hi, we want to integrate humble swapping into our project, how can i get:
1. pool info (input = asa_1_id + asa_2_id)
2. txns (input = pool info + asa_1_amount)
// txns will be sent to frontend user for signing with wallet.

i can do swapping with sdk, but only need the txns(no need to send):
https://github.com/reach-sh/humble-sdk/blob/7368e1ebd0223b7c2511260f9169b8fd0b8e45f1/src/api/Trader.Swap.ts#L17

**Comment by MrJackdaw** [comment]
Hey @nnnggel; you don't need to send transactions directly to the user's wallet. The SDK uses the same [**account abstraction object**](https://docs.reach.sh/frontend/#ref-frontends-js-acc) that you get from `@reach-sh/stdlib`. 


### Getting an `Account` object
When using reach stdlib with Algorand, you can usually use WalletConnect or MyAlgoWallet. Here's how you initialize the SDK with wallet options.

#### WalletConnect 
Using this looks almost exactly the same as MyAlgoWallet, except the wallet fallback object will be `{ WalletConnect }`.\
You will need to install `@reach-sh/stdlib@0.1.10-rc.6` separately if you want to use `WalletConnect`.  There's a section [**here**](https://docs.reach.sh/frontend/#ref-frontends-js-provider) that shows how you could  import the `WalletConnect` object from reach stdlib; just supply it as a wallet fallback as shown above. If you want *both* WC and MAW as options, consider doing this to get both imports. If you want only MyAlgoWallet, read on.

#### MyAlgo
You can install and use the `MyAlgoConnect` package from randlabs when initializing HumbleSDK. 
```typescript
import  { createReachAPI, initHumbleSDK } from "@reach-sh/humble-sdk";
import MyAlgoConnect from "@randlabs/myalgo-connect"; // get this from npm 

initHumbleSDK({
  // include your usual options here (e.g. network), then add this for the wallet:  
  walletFallback: { MyAlgoConnect }
});

const stdlib = createReachAPI()

// Connect the wallet: you should only need to do this once. Store and use this 
// reference wherever the SDK asks for a "ReachAccount" 
const account = await stdlib.getDefaultAccount()
```

#### Mnemonic
This is another way to get an account if e.g. you are using a command-line or other windowless environment. 

```typescript
import  { createReachAPI, initHumbleSDK } from "@reach-sh/humble-sdk";

// Initialize SDK WITHOUT wallet options (i.e. what you were doing before)
initHumbleSDK({ ... });

const stdlib = createReachAPI();

// Connect an account using a mnemonic phrase. You can get this from
// e.g. a command-line input or an environment variable
const mnemonic = process.env.MY_MNEMONIC; // string
const account = await stdlib.newAccountFromMnemonic( mnemonic );
```

Any one of these should allow you to use any part of the SDK. 

### Using the `Account` abstraction 

#### Fetching pools
Most operations require pool and/or token data. We recommend using the [`subscribeToPoolStream`](https://reach-sh.github.io/humble-sdk/METHODS.html#subscribetopoolstream) function here, though instead of using `stdlib.createAccount()`, you should supply the `account` from one of the examples above. 
```typescript
subscribeToPoolStream( account, { ... } )
```
That function will emit objects that look like this **for each pool**: you can see both the condensed pool data, as well as the metadata for the tokens in the pool. You will need to store a list of these objects so they can be referenced later. 
```json
{
    "pool": {
        "poolAddress": 94291765,
        "poolTokenId": 94291788,
        "mintedLiquidityTokens": 34884660669,
        "n2nn": false,
        "tokenABalance": "3488466.30159452",
        "tokenAFees": "0",
        "tokenAId": 94110718,
        "tokenADecimals": 8,
        "tokenBBalance": "3488467",
        "tokenBFees": "0",
        "tokenBId": 94288609,
        "tokenBDecimals": 0
    },
    "tradeable": true,
    "tokens": [
        {
            "id": 94110718,
            "name": "Hubles",
            "symbol": "HBL",
            "url": "",
            "supply": "50000000",
            "decimals": 8
        },
        {
            "id": 94288609,
            "name": "Kornflakes",
            "symbol": "KORN",
            "url": "",
            "supply": "50000000",
            "decimals": 0
        }
    ]
}
```
You can now use this object as the `pool` const shown in the [**swap examples here**](https://reach-sh.github.io/humble-sdk/SWAPPING.html#swaptokens). Hope this helps!

**Comment by nnnggel** [comment]
@MrJackdaw Thank you for your fast reply.

I'm dev of althena(althena.io, a dex aggregator).

Althena consists of two parts:
frontend - UI
backend - calculation (distribute the proportion of transactions according to the depth of multiple dex)


The process of althena is as follow:
1. frontend pass asa_1_id/asa_2_id/asa_1_amount to backend
2. backend get pool infos of multiple dexes -> calculate -> assign different proportions(e.g. 80% in humble + 20% in pact) -> assemble txns of swapping(e.g. 2 humble's + 2 pact's) -> return to frontend
3. user sign txns which return by above step with wallet(myalgo/algosigner/...)

** we will assign part of the amount in humble if it's composable.
** we will assign all amount in humble if it's not composable.
** we are not using reach.

We're stuck getting humble(swapping) txns, it will be appreciate if you help us resolve the problem.

**Comment by nnnggel** [comment]
@MrJackdaw Thank you for your fast reply.

I'm dev of althena(althena.io, a dex aggregator).

Althena consists of two parts:
frontend - UI
backend - calculation (distribute the proportion of transactions according to the depth of multiple dex)


The process of althena is as follow:
1. frontend pass asa_1_id/asa_2_id/asa_1_amount to backend
2. backend get pool infos of multiple dexes -> calculate -> assign different proportions(e.g. 80% in humble + 20% in pact) -> assemble txns of swapping(e.g. 2 humble's + 2 pact's) -> return to frontend
3. user sign txns which return by above step with wallet(myalgo/algosigner/...)

** we will assign part of the amount in humble if it's composable.
** we will assign all amount in humble if it's not composable.
** we are not using reach.

We're stuck getting humble(swapping) txns, it will be appreciate if you help us resolve the problem.

**Comment by nnnggel** [comment]
I don't know if it is possible that obtaining txns through humble-sdk exporting (current 'swapTokens' includes assembling txns + sending).
or maybe some API ways?

**Comment by nnnggel** [comment]
get it, thank you.

**Comment by nnnggel** [comment]
one more question, are swapping transactions of humbleswap composable?

**Comment by jeapostrophe** [comment]
That's not what "composable" means. We are composable, because we are ABI-compliant and allow swapping on-chain using the ABI. We do not allow extra transactions in the group.

**Comment by nnnggel** [comment]
Different perspectives have different understandings of composability. For an aggregator, it's "uncomposable" when it cannot be packaged with other dexes transactions in a group (atomicity transaction).

**Comment by jeapostrophe** [comment]
That is the definition of "composability" in all other blockchains and in all other software systems --- https://en.wikipedia.org/wiki/Function_composition

**Comment by nnnggel** [comment]
Thank you both, I have some clues now, atomic composer can combine ABI well.

I noticed that there are two txns in one group when swapping(algo->usdc):
the first tx is for transfering algo from user to pool (type=transfer),
the second tx is for transfering usdc from pool to user (type=application call).

can you explain the application args in the second tx?

> AA==
> Aw==
> AAAAAAAAAAA=
> AwAAAAAAAYagAAAAAAAAcFMAAAAAAAA

https://algoexplorer.io/tx/MVIY2RD4S3EWP4ZBFX7OI32ZRPDEL3CFO6ZWPBO2CINNQ6BGH7CA

**Comment by jeapostrophe** [comment]
That call didn't use the ABI. You should use the ABI instead
